// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBC1tSWk7Z99WqkL5xwuYJh9XwEJiKRY',
    appId: '1:168769316445:web:de44dbfd6ee5440295cfb4',
    messagingSenderId: '168769316445',
    projectId: 'lawadvisor-6785a',
    authDomain: 'lawadvisor-6785a.firebaseapp.com',
    storageBucket: 'lawadvisor-6785a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAedmMNxlf0BkKB2Ti6CtcCn45GpCCFRc',
    appId: '1:168769316445:android:54c77718b33f143495cfb4',
    messagingSenderId: '168769316445',
    projectId: 'lawadvisor-6785a',
    storageBucket: 'lawadvisor-6785a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHeDkCy7n4AUzby7JGw1_fsgevgumJ-lQ',
    appId: '1:168769316445:ios:cea1f4532e35e5bf95cfb4',
    messagingSenderId: '168769316445',
    projectId: 'lawadvisor-6785a',
    storageBucket: 'lawadvisor-6785a.appspot.com',
    iosBundleId: 'com.example.lawadvisor',
  );
}
